### ISSUE TITLE
watchOS 9.0 - does not connect to HDS Cloud

### ISSUE THREAD

**Issue by beaudamion** [Rexios80/Health-Data-Server-Overlay#63]
**Did you try [these troubleshooting steps?](https://github.com/Rexios80/Health-Data-Server-Overlay/wiki/Troubleshooting)**
Yes/No (If you say no please provide an explanation)

**Hardware/Software**
- iPhone: ex: 13 Pro
- iOS: ex: 16
- Apple Watch: ex: Series 5 44mm
- watchOS: ex: 9
- Windows: ex: Windows 10
- App: ex: 11.6 (1)
- Server: ex: n/a

**To Reproduce**
start hds. overlay says cloud connected on obs. doesn't receive data from watch. watch app shows disconnected to hds cloud.

**Comment by Rexios80** [comment]
Bruh

**Comment by Rexios80** [comment]
This is already fixed. It will be released soon. https://github.com/Rexios80/Health-Data-Server-Overlay/issues/62

**Comment by Rexios80** [comment]
If you want to use it now, join the TestFlight release: https://testflight.apple.com/join/hG4FkmZ4

**Comment by beaudamion** [comment]
(ﾉ◕ヮ◕)ﾉ*:・ﾟ✧

**Comment by beaudamion** [comment]
Just tried the TestFlight release with RTD Fallback and it still doesn't seem to connect.

Anything I can test on my end? watch connected to wifi / phone.. etc.

**Comment by Rexios80** [comment]
Did you enable RTD Fallback on the overlay?

**Comment by beaudamion** [comment]
RTD switch didn't stay on / saved in the browser source in obs for some reason. Sorry for bothering you and Thanks for getting back so quick. 👍

**Comment by Rexios80** [comment]
The switch does stay on now right?

**Comment by beaudamion** [comment]
im actually restarting the computer to test. Only use the rig for streaming / etc...

**Comment by beaudamion** [comment]
doesn't seem to save as switched on in the browser source... Everything else does. Don't know if it's a OBS 28 issue.. or caching issue...

**Comment by Rexios80** [comment]
I doubt it's an OBS issue. Let me check what's wrong.

**Comment by beaudamion** [comment]
deleting browser source / scene collection and re-adding seemed to have fixed the issue.. Saves the RTD switch setting now on restart.

**Comment by Rexios80** [comment]
It looks like it's working for me. Maybe it actually is an OBS issue? Do any other settings persist?

**Comment by Rexios80** [comment]
Maybe it's an issue with having the data from the old overlay and then getting the new version

**Comment by Rexios80** [comment]
Now I kind of wish we had debugged it so I knew what the problem was, but I guess that will have to wait until someone else has the issue
